## Import Necessary Libraries

In [1]:
import numpy as np

##  The Basic

In [2]:
a = np.array([1,2,3],dtype ='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[1.0,2.0,4.0],[3.0,7.0,9.0]])
print(b)

[[1. 2. 4.]
 [3. 7. 9.]]


In [4]:
#Get Dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#Get Shape
a.shape,b.shape

((3,), (2, 3))

In [7]:
#Get Type
a.dtype

dtype('int16')

In [8]:
a.dtype

dtype('int16')

In [9]:
#Get Size
a.itemsize

2

In [10]:
a.nbytes

6

## Accessing.Changing specific elements,rows,columns, etc

In [33]:
a = np.array([[1,4,6,7,8,9,7],[3,5,3,6,4,7,8]])
print(a)

[[1 4 6 7 8 9 7]
 [3 5 3 6 4 7 8]]


In [12]:
#Get a specfic element [r,c]
a[1,6]

8

In [13]:
#Get a specfic row
a[0:1]

array([[1, 4, 6, 7, 8, 9, 7]])

In [14]:
#Get a specific column
a[:,2]

array([6, 3])

In [15]:
#Getting a little more fancy [Startindex.endindex:stepsize]

a[1,1:7:2]

array([5, 6, 7])

In [16]:
a[0,1:-2:2]

array([4, 7])

In [17]:
a[0,5] = 15
print(a)
a[:,4] = [1,2]
print(a)

[[ 1  4  6  7  8 15  7]
 [ 3  5  3  6  4  7  8]]
[[ 1  4  6  7  1 15  7]
 [ 3  5  3  6  2  7  8]]


#### 3-D example

In [18]:
b = np.array([[[1,2],[3,4]],[[2,4],[3,5]]])
print(b)

[[[1 2]
  [3 4]]

 [[2 4]
  [3 5]]]


In [19]:
# Get specfic element (work outside in)
b[0,1,0]

3

In [22]:
b[:,0,:]

array([[1, 2],
       [2, 4]])

In [25]:
# Replace
b[:1,:] = [[9,9],[8,8]]
print(b)

[[[9 9]
  [8 8]]

 [[2 4]
  [3 5]]]


### Initailizing Different Types Of Arrays

In [28]:
# All 0s matrix
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
#ALL is matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
# Any  other number
np.full((2,2,2),99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [36]:
# Any other number (full_like)
np.full_like(a,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [37]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.922869  , 0.70484275],
       [0.2651404 , 0.66803974],
       [0.48755586, 0.4843118 ],
       [0.13103156, 0.45544584]])

In [43]:
np.random.random_sample(a.shape)

array([[0.5027083 , 0.14466412, 0.71045582, 0.37736275, 0.21217713,
        0.45352692, 0.2975013 ],
       [0.0128926 , 0.12426974, 0.32565875, 0.94820324, 0.82739691,
        0.86515545, 0.51785497]])

In [44]:
# Random Integer values
np.random.randint(7,size=(3,3))

array([[2, 0, 4],
       [4, 3, 4],
       [5, 3, 4]])

In [45]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
#Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [49]:
arr = np.array([[1,2,3]])
r2= np.repeat(arr,3,axis=1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]


In [57]:
output = np.ones((5,5))
print(output)
z  = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
#Be careful when copying arrays

In [61]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


[100   2   3]


### Mathematics

In [63]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [64]:
a + 2

array([3, 4, 5, 6])

In [65]:
a - 2

array([-1,  0,  1,  2])

In [66]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [67]:
a * 5

array([ 5, 10, 15, 20])

In [70]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [71]:
b = np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [73]:
a ** 4

array([  81,  256,  625, 1296], dtype=int32)

In [74]:
#Take the sin
np.sin(b)

array([0.84147098, 0.        , 0.84147098, 0.        ])

In [75]:
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

### Linear Algebra

In [76]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [80]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [81]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [82]:
stats = np.array([[1,2,3],[2,4,6]])
stats

array([[1, 2, 3],
       [2, 4, 6]])

In [83]:
stats.min()

1

In [84]:
stats.max()

6

In [87]:
np.mean(stats)

3.0

In [88]:
np.median(stats)

2.5

In [89]:
np.min(stats,axis=1)

array([1, 2])

In [90]:
np.sum(stats)

18

### Reorganizing Arrays

In [91]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [92]:
# Vertically Stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([3,6,8,9])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [3, 6, 8, 9]])

In [93]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [3, 6, 8, 9],
       [3, 6, 8, 9],
       [1, 2, 3, 4]])

In [95]:
# Horizontal Stack
h1 = np.array([1,2,3,4])
h2 = np.array([3,6,8,9])
np.hstack([h1,h2,h2])


array([1, 2, 3, 4, 3, 6, 8, 9, 3, 6, 8, 9])

In [96]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])